apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000 
      nodePort: 30432
  selector:
    tier: frontend 