apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend 
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend 
  template:
    metadata:
      labels:
        tier: frontend 
    spec:
      containers:
        - name: dtr-fe 
          image: dtr-fe
          imagePullPolicy: "Never"
          ports:
            - containerPort: 3000 