version: '3.4'

services:
  dtr.db:
    image: postgres
  pgadmin:
    image: dpage/pgadmin4
  rabbitmq:
    image: masstransit/rabbitmq:3.9

volumes:
  postgres_data:
  pgadmin_data:
  rabbitmq_data:

networks:
  local-dev-net:
